config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :attendees, :controller => 'event_attendees'

    collection do
      get :latest
      post :bulk_update
    end

    member do
      get :dashboard
    end
  end
  namespace :admin do
    resources :events
  end

  root 'events#index'

end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :find_event

  def index
    @attendees = @event.attendees

  end

  def show
    @attendee = @event.attendees.find( params[:id])
  end

  def new
    @attendee = @event.attendees.build
  end
  def create
    @attendee = @event.attendees.build( attendee_params)
    if @attendee.save
      redirect_to event_attendees_url( @event)
    else
      render :action => :new
    end
  end
  def edit
    @attendee = @event.attendees.find( params[:id])
  end

  def update
    @attendee = @event.attendees.find( params[:id])

    if @attendee.update( attendee_params)
      redirect_to event_attendees_url(@event)
    else
      render :action => :edit
    end
  end

  def destroy
    @attendee = @event.attendees.find( params[:id])
    @attendee.destroy
    redirect_to event_attendees_url(@event)
  end

  protected

  def find_event
    @event = Event.find( params[:event_id])
  end

  def attendee_params
    params.require(:attendee).permit(:name)
  end
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/views/event_attendees/_form.html.erb
<% f.collection_select( :category_id, Category.all, :id, :name) %>

app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee), :method => :patch  do |f| %>
   <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_attendees/index.html.erb
<ul>
  <% @attendees.each do |attendee| %>
    <li>
      <%= attendee.name %>
      <%=link_to 'show', event_attendee_path(@event, attendee), :class => "btn btn-primary" %>
      <%= link_to 'edit', edit_event_attendee_path(@event, attendee), :class => "btn btn-default" %>
      <%= link_to 'destroy', event_attendee_path(@event, attendee), :method => :delete, :data => { :confirm => "Are you sure?"}, :class => "btn btn-danger" %>
    </li>
  <% end %>
</ul>

<%= link_to 'New attendee', new_event_attendee_path(@event), :class => "btn btn-primary" %>
<%= link_to 'Back to index', events_path, :class => "btn btn-primary" %>

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
  <%= f.submit %>
  </div>
<% end %>

app/views/event_attendees/show.html.erb
<h2><%= @event.name %>: Attendee List</h2>
<p><%= @attendee.name %></p>
<%= link_to "Back to index", event_attendees_path(@event) %>