config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :attendees, :controller => 'event_attendees'

    collection do
      get :latest
      post :bulk_update
    end

    member do
      get :dashboard
    end
  end
  namespace :admin do
    resources :events
  end

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name
  belongs_to :user

  has_many :attendees
  belongs_to :category
  has_one :location
  has_many :event_groupships
  has_many :groups, :through => :event_groupships
  delegate :name, :to => :category, :prefix => true, :allow_nil => true
  accepts_nested_attributes_for :location, :allow_destroy => true, :reject_if => :all_blank
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin
  layout "admin"
  def index
    @event = Event.all
  end

  def check_admin
    unless current_user.admin?
      raise ActiveRecord::RecordnotFound
      redirect_to root_path
      return
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :set_event, :only => [:show, :edit, :update, :destroy, :dashboard]
  private
  def set_event
    @event = Event.find(params[:id])
  end
  def event_params
    params.require(:event).permit(:name, :description, :category_id, :status, :group_ids => [])
  end

  public
  # GET /events/index
  # GET /events
  def index
    if params[:eid]
      @event = Event.find( params[:eid])
    else
      @event = Event.new
      # @event.start_on = Date.new(2015,1,1)
    end
    prepare_variable_for_index_template

    respond_to do |format|
      format.html
      format.xml {
        render :xml => @events.to_xml
      }
      format.json {
        render :json => @events.to_json
      }
      format.atom {
        @feed_title = "My event list"
      }
    end
  end
  # GET /events/:id/dashboard
  def dashboard

  end
  def latest
    @events =Event.order("id DESC").limit(3)

  end
  # POST /event.bulk_delete
  def bulk_update
    ids = Array( params[:ids])
    events = ids.map{ |i| Event.find_by_id(i)}.compact
    if params[:commit] == "Delete"
      events.each { |event| event.destroy}
    elsif params[:commit] =="Publish"
      events.each {|event| event.update( :status => "published")}
    end
    redirect_to :back
  end
  # GET /events
  def show
    @page_title = @event.name
    respond_to do |format|
      format.html { @page_title = @event.name } # show.html.erb
      format.xml # show.xml.builder
      format.json { render :json => { id: @event.id, name: @event.name }.to_json }
    end
  end
  # GET /events/new
  def new
    @event = Event.new
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    # @event.user = current_user
    if @event.save
      flash[:notice] = "Successfully created!"
      # Do not what confirmation alert
      redirect_to events_path #Tell browser HTTP code: 303
    else
      render :action => :new
    end
  end
  # GET /events/:id/edit
  def edit
  end
  # PATCH /events/:id
  def update
    if @event.update(event_params)
      flash[:notice] = "event was successfully updated!"
      redirect_to event_path(@event)
    else
      render :action => :edit # edit.html.erb
    end
  end
  # DELETE /events/destroy/:id
  def destroy
    @event.destroy
    flash[:alert] = "event was successfully deleted"
    redirect_to events_path
  end
  def prepare_variable_for_index_template
    if params[:keyword]
      @events = Event.where( ["name like ?", "%#{params[:keyword]}%"])
    else
      @events = Event.all
    end

    if params[:order]
      sort_by = (params[:order] == "name") ? "name" : "id"
      @events = @events.order(sort_by)

    end
    @events = @events.page( params[:page]).per(10)
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

<div class="form-group">
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, :required => true, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :status, "Status" %>
  <%= f.select :status, [["Published", "published"], ["Draft", "draft"]] %>
</div>
<div class="form-group">
  <%= f.label :category, "Category" %>
  <%= f.collection_select :category_id, Category.all, :id, :name, :class => "form-control", :include_blank => "Please select" %>
</div>
<div class="form-group">
  <%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>
</div>
<div class="form-group">
  <%= f.label :description, "Description" %>
  <%= f.text_area :description, :class => "form-control" %>
</div>

app/views/events/dashboard.html.erb
<%= @event.name %>'s Dashboard

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :patch do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>

    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<h1> Event list</h1>
<p>
    <%= link_to "Latest events", latest_events_path %>
</p>
<%= form_for @event do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit "Save", :class => "btn btn-primary" %>
  <%= link_to "Cancel", events_path, :class => "btn btn-default" %>
<% end %>
<%= form_tag events_path, :method => :get do %>
<%= text_field_tag "keyword" %>
<%= submit_tag "Search" %>
<% end %>
<%= form_tag bulk_update_events_path do %>

<%= link_to "Sort by Name", events_path( :order => "name") %>
<%= link_to "Sort by Default", events_path %>
  <table class="table">
  <% @events.each do |event| %>
    <tr>
      <td>
      <%= check_box_tag "ids[]", event.id, false %>
        <%= event.name %>
      </td>
      <td>
          <%= event.user.try(:short_name) %>
      </td>
      <td>
        <%= link_to 'Show', event_path(event), :class => "btn btn-primary" %>
        <%= link_to "Dashboard", dashboard_event_path(event), :class => "btn btn-primary" %>
        <%= link_to 'Attendee List', event_attendees_path(event), :class => "btn btn-primary" %>
        <%= link_to "Get XML", event_path(event, :format => :xml), :class => "btn btn-default" %>
        <%= link_to "Get JSON", event_path(event, :format => :json), :class => "btn btn-default" %>
        <%= link_to 'Edit', edit_event_path(event), :class => "btn btn-default" %>
        <%= link_to 'Delete', event_path(event), :method => :delete, :class => "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
  </table>

  <%= submit_tag "Delete" %>
  <%= submit_tag "Publish" %>
<% end %>
<%= paginate @events %>

app/views/events/latest.html.erb
<% @events.each do |event| %>
  <%= event.name %>
<% end %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path, :class =>"form" do |f| %>
   <%= render :partial => "form", :locals => { :f => f } %>

    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>
<p><%= @event.status %></p>
<ul>
<% @event.groups.each do |g| %>
  <li><%= g.name %></li>
<% end %>
</ul>
<p><%= @event.category_name %></p>

<%= simple_format(@event.description) %>
<p>
  <%= link_to 'Back to index', events_path %>
</p>