config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :attendees, :controller => 'event_attendees'

    collection do
      get :latest
      post :bulk_update
    end

    member do
      get :dashboard
    end
  end
  namespace :admin do
    resources :events
  end

  root 'events#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Rails Project" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-12">

    <h1>Admin Interface</h1>
      <% if flash[:notice].present? %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] .present? %>
        <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
      <% end %>
      <%= yield %>
      <% if current_user && current_user.admin? %>
        <%= link_to "admin", admin_events_path %>
      <% end %>

    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Rails Project" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% if flash[:notice].present? %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] .present? %>
        <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
      <% end %>

      <% if current_user %>
      Hi, <%= current_user.email %>
        <%= link_to('Log out', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('Reset password', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to('Register', new_registration_path(:user)) %> |
        <%= link_to('Login', new_session_path(:user)) %>
      <% end %>
      <%= yield %>
      <%= link_to "admin", admin_events_path %>
    </div>
  </div>
</div>
</body>
</html>